Issue/12 add news
levzakharov/itis-webapp pull request #65
Opened 2017-05-20 10:10 UTC by SoftIlnyr

Добавил загрузку нескольких изображений для одного поста, плюс разграничение доступа по ролям

2017-05-20 16:13 UTC, GoodBoy962 requested changes
Есть, что изменить

2017-05-20 16:13 UTC, GoodBoy962 commented on src/main/java/com/itis/config/WebSecurityConfig.java
> +                .antMatchers("/news/new",  "news/update/**", "news/delete/**").hasAnyRole("ADMIN", "WORKER")
используй ApplicationsUrls

2017-05-20 16:13 UTC, GoodBoy962 commented on src/main/java/com/itis/controller/PostController.java
> +    public String deletePost(@ModelAttribute(name = "post") PostForm postForm, @PathVariable long post_id) {
я уже говорил про названия переменных

2017-05-20 16:13 UTC, GoodBoy962 commented on src/main/java/com/itis/controller/PostController.java
> +        return "redirect:/news";
ApplicationUrls

2017-05-20 16:13 UTC, GoodBoy962 commented on src/main/java/com/itis/controller/StorageController.java
> +@Controller
RestController и тогда ResponseBody не надо будет указывать

2017-05-20 16:13 UTC, GoodBoy962 commented on src/main/java/com/itis/controller/StorageController.java
> +    @GetMapping("/files/{filename:.+}")
ApplicationUrls

2017-05-20 16:13 UTC, GoodBoy962 commented on src/main/java/com/itis/controller/StorageController.java
> +    public ResponseEntity<Resource> serveFile(@PathVariable String filename) {
fileName

2017-05-20 16:13 UTC, GoodBoy962 commented on src/main/java/com/itis/controller/api/PostApiController.java
> +    public ResponseEntity deletePost(@RequestBody Post post) {
логичнее принимать просто id поста

2017-05-20 16:13 UTC, GoodBoy962 commented on src/main/java/com/itis/controller/api/PostApiController.java
>      @GetMapping(value = ApplicationUrls.ApiUrls.BASE_NEWS_URL + "/{postId}")
создавай новый урлы

2017-05-20 16:13 UTC, GoodBoy962 commented on src/main/java/com/itis/controller/api/PostApiController.java
> +    @RequestMapping(value = ApplicationUrls.ApiUrls.BASE_NEWS_URL, method = RequestMethod.GET)
GetMapping

2017-05-20 16:13 UTC, GoodBoy962 commented on src/main/java/com/itis/controller/api/PostApiController.java
> +    public List<Post> postIndexApi() {
убери api из названия и поменяй названия метода в сервисе.

2017-05-20 16:13 UTC, GoodBoy962 commented on src/main/java/com/itis/service/ImageService.java
> +    Image createImage(String name);
почему не void?

2017-05-20 16:13 UTC, GoodBoy962 commented on src/main/java/com/itis/storage/StorageProperties.java
> +    private String location = "src/main/resources/upload-dir";
мне кажется это константа

2017-05-20 16:13 UTC, GoodBoy962 commented on src/main/resources/db/changelog.xml
> +    <include file="changelog/initial/image.xml" relativeToChangelogFile="true"/>
это уже не initial. это custom

2017-05-20 21:10 UTC, SoftIlnyr commented on src/main/java/com/itis/storage/StorageProperties.java
> +    private String location = "src/main/resources/upload-dir";
Куда мне ее закинуть?

2017-05-20 21:13 UTC, GoodBoy962 commented on src/main/java/com/itis/storage/StorageProperties.java
> +    private String location = "src/main/resources/upload-dir";
не закидывать. А сделать private static final String LOCATION = ...

2017-05-20 21:31 UTC, SoftIlnyr commented
Замечания исправил.
P.S.: Ты написал замечания и закрыл пул реквест. Я не увидел их, так как подумал, что ветку замерджили. Не надо так)

2017-05-20 22:33 UTC, SoftIlnyr commented on src/main/java/com/itis/storage/StorageProperties.java
> +    private String location = "src/main/resources/upload-dir";
исправил

2017-05-21 11:37 UTC, levzakharov commented
Разберитесь с конфликтами

2017-05-21 13:27 UTC, GoodBoy962 requested changes

2017-05-21 13:27 UTC, GoodBoy962 commented on src/main/java/com/itis/utils/ApplicationUrls.java
> +        String UPDATE_NEWS_URL = BASE_NEWS_URL + "/update/{postId}";
сначала postId, потом действие. А лучше без действий в урле и воспользуйся глаголами DELETE и PUT

2017-05-21 21:24 UTC, SoftIlnyr commented
Убрал merge конфликты. ПОЖАЛУЙСТА, СДЕЛАЙТЕ **MERGE**!!!

2017-05-21 21:40 UTC, GoodBoy962 commented
не вижу новых коммитов

2017-05-21 21:58 UTC, GoodBoy962 requested changes

2017-05-21 21:58 UTC, GoodBoy962 commented on src/main/java/com/itis/config/WebSecurityConfig.java
> +        ;
в этом файле изменения не нужны

2017-05-21 21:58 UTC, GoodBoy962 commented on src/main/java/com/itis/Application.java
> +//@EnableAutoConfiguration(exclude = {FreeMarkerAutoConfiguration.class})
почему убрал?

2017-05-21 21:58 UTC, GoodBoy962 commented on src/main/java/com/itis/controller/NewsController.java
> -public class NewsController {
если урлы news, то и контроллер должен быть NewsController.

2017-05-21 21:58 UTC, GoodBoy962 commented on src/main/java/com/itis/controller/PostController.java
> +public class PostController {
NewController

2017-05-21 21:58 UTC, GoodBoy962 commented on src/main/java/com/itis/service/ImageService.java
> +    Image createImage(String name);
так и не получил ответа

2017-05-21 21:58 UTC, GoodBoy962 commented on src/main/java/com/itis/service/impl/PostServiceImpl.java
> +            for (MultipartFile multipartFile : postCreationForm.getImages()) {
кажется можно заменить лямбдой

2017-05-21 21:58 UTC, GoodBoy962 commented on src/main/java/com/itis/storage/StorageController.java
> +
таких контроллеров не делают. Имею в виду чисто для файлов. Если для картинок в новостях, то они должны загружаться вместе с формой

2017-05-21 21:58 UTC, GoodBoy962 commented on src/main/java/com/itis/storage/StorageException.java
> +package com.itis.storage;
такой пакет не нужен. Лучше создай в utils все нужное. А для исключений отдельный пакет

2017-05-21 21:58 UTC, GoodBoy962 commented on src/main/java/com/itis/utils/ApplicationUrls.java
> +        String UPDATE_NEWS_URL = BASE_NEWS_URL + "/update/{postId}";
{postId}/update
{postId}/delete

2017-05-21 21:58 UTC, GoodBoy962 commented on src/main/resources/db/changelog.xml
> +    <include file="changelog/custom/image.xml" relativeToChangelogFile="true"/>
почему они добавлены между? они должны быть после коммента custom

2017-05-21 22:11 UTC, GoodBoy962 commented on src/main/java/com/itis/controller/PostController.java
> +        Post post = postService.getById(postId);
почему не сделать просто postService:delete(Long id) ?

2017-05-21 22:12 UTC, GoodBoy962 commented on src/main/java/com/itis/controller/api/NewsApiController.java
> +    @ApiOperation("Get post by id")
давай в контроллерах оставим новости. Посты на уровне сервиса и ниже

2017-05-21 22:13 UTC, GoodBoy962 commented on src/main/java/com/itis/storage/StorageService.java
> +    void init();
для чего?

2017-05-21 22:14 UTC, GoodBoy962 commented on src/main/java/com/itis/storage/StorageService.java
> +public interface StorageService {
мне кажется можно уменьшить количество методов

2017-05-21 22:14 UTC, GoodBoy962 commented on src/main/java/com/itis/storage/StorageService.java
> +public interface StorageService {
да и вообще это не сервис, а утильный класс со статик методами

2017-05-21 22:22 UTC, SoftIlnyr commented on src/main/java/com/itis/config/WebSecurityConfig.java
> +        ;
Я тут ничего не трогал

2017-05-21 22:26 UTC, SoftIlnyr commented on src/main/java/com/itis/controller/PostController.java
> +        Post post = postService.getById(postId);
Тут не понял вопроса, здесь ведь update

2017-05-21 22:27 UTC, GoodBoy962 commented on src/main/java/com/itis/config/WebSecurityConfig.java
> +        ;
почему есть изменения тогда?

2017-05-21 22:28 UTC, GoodBoy962 commented on src/main/java/com/itis/controller/PostController.java
> +        Post post = postService.getById(postId);
не туда написал. Это к следующему методу. Тут зачем ты достаешь пост? создай метод postService:update(postId, form)

2017-05-21 22:28 UTC, GoodBoy962 commented on src/main/java/com/itis/controller/PostController.java
> +        Post post = postService.getById(postId);
коммент выше

2017-05-21 22:28 UTC, SoftIlnyr commented on src/main/java/com/itis/service/impl/PostServiceImpl.java
> +            for (MultipartFile multipartFile : postCreationForm.getImages()) {
Считаю, что лучше оставить рабочий вариант

2017-05-21 22:28 UTC, SoftIlnyr commented on src/main/java/com/itis/service/impl/PostServiceImpl.java
> +            for (MultipartFile multipartFile : postCreationForm.getImages()) {
Пока что

2017-05-21 22:37 UTC, SoftIlnyr commented on src/main/java/com/itis/storage/StorageController.java
> +
Здесь контроллер нужен для отображения картинок
Тут мы прописываем, по какому пути сможем их найти

2017-05-21 22:38 UTC, GoodBoy962 commented on src/main/java/com/itis/storage/StorageController.java
> +
присылай url картинки и доставай по ссылке

2017-05-21 22:39 UTC, GoodBoy962 commented on src/main/java/com/itis/service/impl/PostServiceImpl.java
> +            for (MultipartFile multipartFile : postCreationForm.getImages()) {
внизу у тебя ест лямбды

2017-05-21 22:40 UTC, GoodBoy962 commented on src/main/java/com/itis/controller/NewController.java
> +public class NewController {
NewsController.

2017-05-21 22:40 UTC, GoodBoy962 commented on src/main/java/com/itis/controller/NewController.java
> +public class NewController {
переименую и смерджся

2017-05-21 22:44 UTC, SoftIlnyr commented on src/main/java/com/itis/controller/NewController.java
> +public class NewController {
Готово

2017-05-21 22:53 UTC, SoftIlnyr commented on src/main/java/com/itis/storage/StorageController.java
> +
Давай пока оставим так

2017-05-21 22:54 UTC, SoftIlnyr commented
Можно сделать мердж, пожалуйста?

2017-05-22 11:54 UTC, merged